<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetflixClone.Domain\NetflixClone.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
    <PackageReference Include="Stripe.net" Version="50.4.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Authentication\Commands\RefreshToken\" />
    <Folder Include="Features\Catalog\Content-genres\Commands\CreateGenre\" />
    <Folder Include="Features\Catalog\Content-genres\Commands\DeleteGenre\" />
    <Folder Include="Features\Catalog\Content-genres\Commands\UpdateGenre\" />
    <Folder Include="Features\Catalog\Content\Commands\UpdateContent\" />
    <Folder Include="Features\Catalog\Content\Queries\GetContentById\" />
    <Folder Include="Features\Catalog\Person\Queries\GetPersonById\" />
    <Folder Include="Features\Catalog\Queries\GetTrendingContent\" />
    <Folder Include="Features\Catalog\Person\Commands\CreatePerson\" />
    <Folder Include="Features\Catalog\Person\Commands\DeletePerson\" />
    <Folder Include="Features\Catalog\Person\Commands\UpdatePerson\" />
    <Folder Include="Features\Engagement\Commands\UpdateRating\" />
    <Folder Include="Features\Engagement\Queries\GetWatchHistory\" />
    <Folder Include="Features\Profiles\Commands\DeleteProfile\" />
    <Folder Include="Features\Profiles\Commands\UpdateProfile\" />
    <Folder Include="Features\Profiles\Queries\GetProfiles\" />
    <Folder Include="Features\Streaming\Queries\PlayContent\" />
    <Folder Include="Features\Subscription-Plans\Commands\UpdatePlans\" />
    <Folder Include="Features\Subscriptions\Commands\UpgradePlan\" />
    <Folder Include="Features\Subscriptions\Queries\GetMySubscription\" />
  </ItemGroup>

</Project>
